import type { Metadata } from "next";
import localFont from "next/font/local";

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

import "./globals.css";

const ceraPro = localFont({
  src: [
    {
      path: "./fonts/CERAPRO-LIGHT.woff",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/CERAPRO-LIGHTITALIC.woff",
      weight: "300",
      style: "italic",
    },
    {
      path: "./fonts/CERAPRO-REGULAR.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/CERAPRO-REGULARITALIC.woff",
      weight: "400",
      style: "italic",
    },
    {
      path: "./fonts/CERAPRO-MEDIUM.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/CERAPRO-MEDIUMITALIC.woff",
      weight: "500",
      style: "italic",
    },
  ],
  variable: "--font-cera-pro",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ceraPro.variable} lg:container font-cerapro flex flex-col min-h-screen antialiased`}
      >
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
