name: Pull Request

on:
  pull_request:

concurrency:
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml

  check-types:
    uses: ./.github/workflows/check-types.yaml

